openapi: 3.1.0
info:
  title: Magaya DFP Admin API
  version: '4.0'
  description: ''
servers:
  - url: 'https://api.qwykportals.com/api'
    description: Production
  - url: 'https://api.next.qwykportals.com/api'
    description: Staging
  - url: 'https://api.beta.qwykportals.com/api'
    description: Beta
paths:
  /hub/settings-v2/payment-providers:
    get:
      summary: Payment Providers Index
      tags:
        - Settings
      responses: {}
      operationId: get-settings-payment-providers
      x-internal: false
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                data:
                  type: array
                  items:
                    $ref: '#/components/schemas/PaymentProvider'
    post:
      summary: Payment Providers Create
      operationId: post-settings-payment-providers
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/PaymentProvider'
                  oauth_exchange_token:
                    type: string
                    description: 'Token to complete the OAuth exchange for Veem, only returned when enable_oauth is try in the provider configuration'
                required:
                  - data
      tags:
        - Settings
      x-internal: true
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                payment_provider:
                  type: string
                  enum:
                    - veem
                is_active:
                  type: boolean
                configuration:
                  oneOf:
                    - $ref: '#/components/schemas/VeemPaymentProviderConfiguration'
                    - $ref: '#/components/schemas/PaymentProviderConfiguration'
              required:
                - payment_provider
                - is_active
                - configuration
    parameters: []
  /console/hub-api-clients:
    get:
      summary: Hub API Clients Index
      tags:
        - Console
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/HubApiClient'
                  links:
                    $ref: ./PaginationLinks.yaml
                  meta:
                    $ref: ./PaginationMeta.yaml
      operationId: get-console-hub-api-clients
      x-internal: true
      parameters:
        - schema:
            type: integer
            minimum: 1
            default: 1
          in: query
          name: page
        - schema:
            type: integer
            default: 25
          in: query
          name: pageSize
    parameters: []
    post:
      summary: Hub API Client Create
      operationId: post-console-hub-api-clients-hubApiClientId
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/HubApiClient'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                organization_id:
                  type: integer
                user_id:
                  type: integer
              required:
                - name
                - organization_id
                - user_id
      x-internal: true
      tags:
        - Console
  '/console/hub-api-clients/{hubApiClientId}':
    parameters:
      - schema:
          type: string
        name: hubApiClientId
        in: path
        required: true
    delete:
      summary: Hub API Client Delete
      operationId: delete-console-hub-api-clients-hubApiClientId
      responses:
        '200':
          description: OK
      x-internal: true
  '/console/organizations/{organizationId}/hub-api-clients':
    get:
      summary: Organization API Clients Index
      tags:
        - Console
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/HubApiClient'
                  links:
                    $ref: ./PaginationLinks.yaml
                  meta:
                    $ref: ./PaginationMeta.yaml
      operationId: 'get-console-organizations-:organizationId-api_clients'
      x-internal: true
    parameters:
      - schema:
          type: integer
        name: organizationId
        in: path
        required: true
components:
  schemas:
    PaymentProvider:
      title: PaymentProvider
      type: object
      x-internal: false
      properties:
        id:
          type: string
          format: uuid
        payment_provider:
          type: string
          enum:
            - veem
        configuration:
          oneOf:
            - $ref: '#/components/schemas/VeemPaymentProviderConfiguration'
            - $ref: '#/components/schemas/PaymentProviderConfiguration'
        is_active:
          type: boolean
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
      required:
        - id
        - payment_provider
        - configuration
        - is_active
        - created_at
        - updated_at
    PaymentProviderConfiguration:
      title: PaymentProviderConfiguration
      type: object
      x-internal: false
    VeemPaymentProviderConfiguration:
      title: VeemPaymentProviderConfiguration
      type: object
      x-internal: false
      properties:
        reference_id:
          type: string
          format: uuid
        enable_oauth:
          type: boolean
      required:
        - reference_id
        - enable_oauth
    HubApiClient:
      title: HubApiClient
      x-stoplight:
        id: hgei2lrfmb16s
      type: object
      description: ''
      x-internal: true
      properties:
        name:
          type: string
        client_id:
          type: string
        client_secret:
          type: string
        audience:
          type: string
        organization:
          type: object
          required:
            - id
            - name
          properties:
            id:
              type: integer
            name:
              type: string
        authorizes_as:
          type: object
          required:
            - email
            - name
          properties:
            email:
              type: string
            name:
              type: string
        created_at:
          type: string
          format: date-time
          readOnly: true
        updated_at:
          type: string
          format: date-time
          readOnly: true
      required:
        - name
        - client_id
        - client_secret
        - organization
        - authorizes_as
        - created_at
        - updated_at
  securitySchemes:
    Auth0 Client Credentials:
      type: oauth2
      flows:
        clientCredentials:
          scopes: {}
          tokenUrl: 'https://qwyk.eu.auth0.com/oauth/token'
      description: |-
        Read the docs:
        https://auth0.com/docs/get-started/authentication-and-authorization-flow/client-credentials-flow#introduction
security:
  - Auth0 Client Credentials: []
