openapi: 3.0.0
info:
  title: QwykPortals Quotation API
  version: '1.0'
  contact:
    name: Support
    url: 'https://docs.qwykportals.com'
    email: support@qwyk.io
  license:
    name: Proprietary
  termsOfService: 'http://docs.qwyk.io/docs/legal-terms-of-use.html'
servers:
  - url: 'https://api.next.qwykportals.com'
    description: Next branch
  - url: 'https://api.qwykportals.com'
    description: Stable branch
paths: {}
components:
  schemas: {}
  securitySchemes:
    Bearer token:
      type: http
      scheme: bearer
