openapi: 3.1.0
info:
  title: QwykPortals Warehouse API
  version: '1.0'
servers: []
paths:
  /api/portals/warehouse-receipts:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/WarehouseReceipt'
                  links:
                    $ref: '#/components/schemas/PaginationLinks'
                  meta:
                    $ref: '#/components/schemas/PaginationMeta'
      operationId: get-api-portals-warehouse-receipts
      parameters:
        - schema:
            type: integer
            minimum: 1
            default: 25
          in: query
          name: pageSize
        - schema:
            type: integer
            minimum: 1
            default: 1
          in: query
          name: page
  '/api/portals/warehouse-receipts/{id}':
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/WarehouseReceipt'
      operationId: 'get-api-portals-warehouse-receipts-:id'
    parameters:
      - schema:
          type: string
          format: uuid
        name: id
        in: path
        required: true
components:
  schemas:
    WarehouseReceipt:
      title: WarehouseReceipt
      type: object
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        organization_id:
          type: integer
          readOnly: true
        number:
          type: string
        status:
          type: integer
        status_name:
          type: string
        warehouse:
          type: string
        shipper_name:
          type: string
        consignee_name:
          type: string
        supplier_name:
          type: string
        destination_agent_name:
          type: string
        driver_name:
          type: string
        carrier_pro_number:
          type: string
        carrier_tracking_number:
          type: string
        driver_license_number:
          type: string
        supplier_po_number:
          type: string
        notes:
          type: string
        is_on_hold:
          type: boolean
        created_by:
          type: string
        created_at:
          type: string
          format: date-time
          readOnly: true
        updated_at:
          type: string
          format: date-time
          readOnly: true
        deleted_at:
          type: string
          format: date-time
          readOnly: true
      required:
        - id
        - organization_id
        - number
        - status
        - status_name
        - is_on_hold
        - created_at
        - updated_at
    Event:
      title: Event
      type: object
      properties:
        id:
          type: string
          format: uuid
        parent_type:
          type: string
          enum:
            - warehouse_receipt
        parent_id:
          type: string
          format: uuid
        name:
          type: string
        event:
          type: string
        location_name:
          type: string
        date:
          type: string
          format: date-time
      required:
        - id
        - parent_type
        - parent_id
    CargoItem:
      title: CargoItem
      type: object
      properties:
        id:
          type: string
          format: uuid
        parent_type:
          type: string
          enum:
            - warehouse_receipt
        parent_id:
          type: string
          format: uuid
        status:
          type: integer
        status_name:
          type: string
        type_code:
          type: integer
        count:
          type: integer
        quantity:
          type: integer
        package_name:
          type: string
        description:
          type: string
        location:
          type: string
        weight:
          $ref: '#/components/schemas/UnitValue'
        volume:
          $ref: '#/components/schemas/UnitValue'
        total_value:
          type: object
          properties:
            currency:
              type: string
            amount:
              type: number
        is_child:
          type: boolean
        is_kit:
          type: boolean
        is_container:
          type: boolean
        is_really_a_container:
          type: boolean
        is_vehicle:
          type: boolean
        is_on_hold:
          type: boolean
      required:
        - id
        - parent_type
        - parent_id
    Attachment:
      title: Attachment
      type: object
      properties:
        id:
          type: string
          format: uuid
        parent_type:
          type: string
          enum:
            - warehouse_receipt
        parent_id:
          type: string
          format: uuid
        filename:
          type: string
        description:
          type: string
        mime_type:
          type: string
        extension:
          type: string
        created_at:
          type: string
          format: date-time
      required:
        - id
        - parent_type
        - parent_id
    Entity:
      title: Entity
      type: object
      properties:
        id:
          type: string
          format: uuid
        parent_type:
          type: string
          enum:
            - warehouse_receipt
        parent_id:
          type: string
          format: uuid
      required:
        - id
        - parent_type
        - parent_id
    UnitValue:
      title: UnitValue
      type: object
      properties:
        value:
          type: number
        unit:
          type: string
      x-internal: false
    PaginationLinks:
      description: ''
      type: object
      x-examples:
        example-1:
          first: 'http://api.next.qwykportals.com/api/portals/shipments/v2?page=1'
          last: 'http://api.next.qwykportals.com/api/portals/shipments/v2?page=13'
          prev: null
          next: 'http://api.next.qwykportals.com/api/portals/shipments/v2?page=2'
      properties:
        first:
          type: string
          minLength: 1
        last:
          type: string
          minLength: 1
        prev:
          type: string
        next:
          type: string
          minLength: 1
      required:
        - first
        - last
        - next
    PaginationMeta:
      description: ''
      type: object
      x-examples:
        example-1:
          current_page: 1
          from: 1
          last_page: 13
          links:
            - url: null
              label: '&laquo; Previous'
              active: false
            - url: 'http://api.next.qwykportals.com/api/portals/shipments/v2?page=1'
              label: '1'
              active: true
            - url: 'http://api.next.qwykportals.com/api/portals/shipments/v2?page=2'
              label: '2'
              active: false
            - url: 'http://api.next.qwykportals.com/api/portals/shipments/v2?page=3'
              label: '3'
              active: false
            - url: 'http://api.next.qwykportals.com/api/portals/shipments/v2?page=4'
              label: '4'
              active: false
            - url: 'http://api.next.qwykportals.com/api/portals/shipments/v2?page=5'
              label: '5'
              active: false
            - url: 'http://api.next.qwykportals.com/api/portals/shipments/v2?page=6'
              label: '6'
              active: false
            - url: 'http://api.next.qwykportals.com/api/portals/shipments/v2?page=7'
              label: '7'
              active: false
            - url: 'http://api.next.qwykportals.com/api/portals/shipments/v2?page=8'
              label: '8'
              active: false
            - url: 'http://api.next.qwykportals.com/api/portals/shipments/v2?page=9'
              label: '9'
              active: false
            - url: 'http://api.next.qwykportals.com/api/portals/shipments/v2?page=10'
              label: '10'
              active: false
            - url: 'http://api.next.qwykportals.com/api/portals/shipments/v2?page=11'
              label: '11'
              active: false
            - url: 'http://api.next.qwykportals.com/api/portals/shipments/v2?page=12'
              label: '12'
              active: false
            - url: 'http://api.next.qwykportals.com/api/portals/shipments/v2?page=13'
              label: '13'
              active: false
            - url: 'http://api.next.qwykportals.com/api/portals/shipments/v2?page=2'
              label: Next &raquo;
              active: false
          path: 'http://api.next.qwykportals.com/api/portals/shipments/v2'
          per_page: 25
          to: 25
          total: 323
      properties:
        current_page:
          type: number
        from:
          type: number
        last_page:
          type: number
        links:
          type: array
          uniqueItems: true
          minItems: 1
          items:
            type: object
            properties:
              url:
                type: string
              label:
                type: string
                minLength: 1
              active:
                type: boolean
            required:
              - label
              - active
        path:
          type: string
          minLength: 1
        per_page:
          type: number
        to:
          type: number
        total:
          type: number
      required:
        - current_page
        - from
        - last_page
        - links
        - path
        - per_page
        - to
        - total
  responses: {}
