openapi: 3.0.0
info:
  title: Shipment Exchange API
  version: '1.0'
  contact:
    name: Qwyk
    url: qwyk.io
    email: support@qwyk.io
  description: Describes exchanges related to shipments
servers:
  - url: 'https://api.qwykportals.com'
    description: QwykPortals API (stable)
  - url: 'https://api.next.qwykportals.com'
    description: QwykPortals API (next)
paths:
  /webhooks/portals/shipments/timeline-event:
    post:
      summary: Post Milestone Update
      operationId: post-webhooks-portals-shipments-booking-confirmation
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WebhookResponse'
      security:
        - Bearer Token: []
      description: ''
      tags:
        - Methods
      parameters:
        - schema:
            type: string
            example: 'Bearer [YOUR TOKEN]'
          in: header
          name: Authentication
          description: Pre-assigned bearer token
          required: true
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                doc_type:
                  type: string
                  default: event_json
                version:
                  type: string
                  default: '1.0'
                events:
                  type: array
                  minItems: 1
                  items:
                    $ref: '#/components/schemas/ShipmentEvent'
              required:
                - doc_type
                - version
                - events
        description: ''
    parameters: []
  /webhooks/portals/shipments/booking-confirmation:
    post:
      summary: Post Booking Confirmation
      operationId: post-webhooks-portals-shipments-timeline-event
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WebhookResponse'
      parameters:
        - schema:
            type: string
            example: 'Bearer [YOUR TOKEN]'
          in: header
          name: Authentication
          required: true
          description: Pre-assigned bearer token
      security:
        - Bearer Token: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                version:
                  type: string
                  default: '1.0'
                doc_type:
                  type: string
                  default: chainio_booking_response
                booking_responses:
                  type: array
                  minItems: 1
                  items:
                    type: object
                    properties:
                      notes:
                        type: string
                        example: Booking accepted
                      requesting_party_shipment_reference:
                        type: string
                        description: "Qwyk's internal shipment ID"
                        format: uuid
                        example: f4d2a948-219d-4370-8f4e-b2a8a5ae0ba2
                      responding_party_shipment_reference:
                        type: string
                        maxLength: 255
                        description: Your shipment reference / booking number
                        example: BOL123048882
                      response_date:
                        type: string
                        format: date-time
                        example: '2020-01-29T08:30:07.599Z'
                      response_type:
                        type: string
                        enum:
                          - accept
                          - reject
                        default: accept
                        example: accept
                      transmission_uid:
                        type: string
                    required:
                      - notes
                      - requesting_party_shipment_reference
                      - responding_party_shipment_reference
                      - response_date
                      - response_type
              required:
                - version
                - doc_type
                - booking_responses
      description: ''
      tags:
        - Methods
    parameters: []
  '/{your-endpoint}':
    parameters:
      - schema:
          type: string
        name: your-endpoint
        in: path
        required: true
    post:
      summary: ''
      operationId: post-your-endpoint
      responses:
        '200':
          description: OK
      tags:
        - Webhooks
components:
  schemas:
    WebhookResponse:
      title: WebhookResponse
      type: object
      x-tags:
        - Models
      properties:
        transactionId:
          type: string
          description: Qwyk transaction id
          format: uuid
        message:
          type: string
    ShipmentEvent:
      title: ShipmentEvent
      type: object
      x-tags:
        - Models
      properties:
        source_system_shipment_uid:
          type: string
          description: "Qwyk's shipment id"
        event_code:
          type: string
          description: To be mapped during setup
        estimated_date:
          type:
            - string
            - 'null'
          format: date-time
        actual_date:
          type:
            - string
            - 'null'
          format: date-time
        notes:
          type:
            - string
            - 'null'
        vessel_name:
          type:
            - string
            - 'null'
          maxLength: 191
        voyage_number:
          type:
            - string
            - 'null'
          maxLength: 191
        house_bill:
          type:
            - string
            - 'null'
          maxLength: 191
        master_bill:
          type:
            - string
            - 'null'
          maxLength: 191
        forwarder_reference:
          type:
            - string
            - 'null'
          maxLength: 191
        event_unlocode:
          type: object
          properties:
            unlocode:
              type: string
              minLength: 5
              maxLength: 5
            description:
              type: string
      required:
        - source_system_shipment_uid
        - event_code
  securitySchemes:
    Bearer Token:
      name: Authentication
      type: apiKey
      in: header
      description: ''
